name: game_stairgun

services:
  client:
    image: kyuseishu/game_stairgun
    container_name: ${name}client
    ports:
      - 3000:8080
    build:
      context: .
      dockerfile: dockerfile
networks:
  default:
    driver: game_stairgun
